apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql-db
          image: postgres:latest
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
            requests:
              memory: 256Mi
              cpu: '0.2'
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          envFrom:
          - configMapRef:
              name: postgres-db-config
          ports:
            - containerPort: 80
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 25Gi
